version: '3.8'

services:
  frontend:
    image: ghcr.io/ics-pa-2025/2025_proyecto3_front_claimflow:latest
    container_name: frontend_nuevo_proyecto
    restart: unless-stopped
    ports:
      - '80:80'
    networks:
      - microservices

networks:
  microservices:
    name: nuevo-proyecto-microservices
    external: false